### Signup
POST http://127.0.0.1:8000/signup/ 
Content-Type: application/json

{ "username": "Test", "password": "Pass1234!", "email": "test@mail.com" }


### Login
POST http://127.0.0.1:8000/login/ 
Content-Type: application/json

{ "username": "Test", "password": "Pass1234!" }


# POSTS CRUD -------------------------  

### List all posts
GET http://localhost:8000/posts/
Authorization: token xxxxx


### Retrieve a specific post by ID
GET http://localhost:8000/posts/5/
Authorization: token xxxxx


### Create a new post
POST http://localhost:8000/posts/
Authorization: token xxxxx
Content-Type: application/json

{ "title": "My new amazing post", "content": "Content of my post" }


### Update a specific post by ID
PUT http://localhost:8000/posts/1/
Authorization: Token xxxxx
Content-Type: application/json

{
  "title": "Updated Post Title",
  "content": "Updated content of the post"
}


### Delete a specific post by ID
DELETE http://localhost:8000/posts/1/
Authorization: Token xxxxx


# COMMENTS CRUD

### List all Commnents
GET http://localhost:8000/comments/
Authorization: token xxxxx


### List comments on a post by post's id 
GET http://localhost:8000/comments/5/
Authorization: token xxxxx


### Create a new comment on a post
POST http://localhost:8000/comments/
Authorization: token xxxxx
Content-Type: application/json

{ "post": 5, "content": "a new comment from me" }


### Delete a specific comment by ID
DELETE http://localhost:8000/comments/1/
Authorization: Token xxxxx



### get likes on a specific post by ID
GET http://localhost:8000/likes/325/
Authorization: Token xxxxx


### like a specific post by ID
# one user can only make one like
POST http://localhost:8000/like/
Authorization: Token xxxxx
Content-Type: application/json

{ "pk" : 325 }


