# Generated by Django 5.0.7 on 2024-07-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_liking_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='default', max_length=30),
            preserve_default=False,
        ),
    ]
